/** Generated by Shipdeck from source. Does not replace your own tests. */
import { HealthController } from './modules/health/health.controller';

describe('Shipdeck smoke (api)', () => {
  it('health check returns ok', () => {
    const ctl = new HealthController();
    const res = ctl.check() as { status?: string };
    expect(res.status).toBe('ok');
  });
});
